# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
