# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170715_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
